apiVersion: v1
kind: Service
metadata:
  name: flask-crud
  namespace: flask-crud
spec:
  type: LoadBalancer
  selector:
    app: flask-crud
    role: web
  ports:
    - name: http
      port: 80
      targetPort: gunicorn